server:
  port: 9297
  servlet:
    context-path: /ssr


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_shiro?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root

  thymeleaf:
    cache: false

  mvc:
    static-path-pattern: /static/**
  redis:
    host: 127.0.0.1
    port: 9379
    database: 1


mybatis:
  mapper-locations: classpath:mapper/*.xml

# redisManager过期时间
redis.expire: 1800


